name: Compilation test

on: [push, pull_request]

jobs:
  build:
    name: Build the contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://node:12.14.1
      - run: npm install --include-dev --save-exact
      - run: npm run build
      - run: npm run test
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKENN: ${{ secrets.GITHUB_TOKEN }}
